apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: gblbjj/desafio-node-app:0.0.7
          env:
            - name: HOST
              value: mysql.default.svc.cluster.local
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER      
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - dockerize -wait tcp://mysql.default.svc.cluster.local:3306 -timeout 60s node index.js
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits: 
              memory: "512Mi"
              cpu: "500m"
